#!/usr/bin/env python3
"""THE STRATEGY LEDGER — every logic change, and what happened next.

★★★ Operator, 2026-10-06: *"we absolutely need to know why its improving or getting worse?
all changes in logic and strategy need to be recorded"* / *"otherwise how do we measure
success and failure etc"*.

He is right, and the honest answer to "why" has two halves that must never be merged:

  WHAT CHANGED is knowable exactly. The rule sets are versioned, so the diff is a fact.
  WHY IT MOVED is not knowable from this experiment as it is built. One run per iteration,
  ten rules rewritten at once, and a measured single-run spread of **$324/day** on identical
  inputs — against which iteration 2's **+$111/day** is noise. Anything claiming "rule 1
  caused the gain" from that evidence is a story.

So this ledger records the knowable half completely, and for the unknowable half it reports
the DECOMPOSITION — where in the distribution the money actually moved — plus a
leave-one-day-out check that shows how much of a lead rests on a single session. That is as
far as the data goes, and the file says so in its own text rather than leaving a reader to
assume more.

WHAT IT FOUND ON FIRST RUN, as an example of why the decomposition matters: iteration 2's
whole gain is in the LOSING tail (+$822 of the +$1,110; winners moved only +$288), five days
improved and five got WORSE, and the single day 2026-08-21 (−$1,180 → +$200) is load-bearing
— remove it and iteration 2 is BEHIND iteration 1. "It improved by $111/day" is true and
almost useless; "it stopped having a catastrophic day, and gave back a little on its best
days" is the actual finding.

⚠ REGENERATED FROM THE ARTEFACTS, NEVER HAND-EDITED. A hand-maintained changelog drifts from
what the code did, and then the record of the experiment becomes the least reliable thing in
it. Re-run this after every iteration; it rewrites the file from scratch.
⚠ A POISONED DAY IS EXCLUDED EVERYWHERE — a day the model never answered is not behaviour.
⚠ READ-ONLY on the desk. Reads loop artefacts, writes one markdown file.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import subprocess
import sys

GB = "/home/alphabot/gazbot7"
OUT = f"{GB}/reports/recursive_loop"
SIM = f"{GB}/reports/sim_week_recursive"
DOC = f"{GB}/docs/STRATEGY_LEDGER.md"
HOLD = ["2026-08-17", "2026-08-18", "2026-08-19", "2026-08-20", "2026-08-21",
        "2026-09-14", "2026-09-15", "2026-09-16", "2026-09-17", "2026-09-18"]
RUN_VARIANCE = 324.0
POISON = 0.10


def day_rows(tag: str) -> dict:
    out = {}
    for d in HOLD:
        p = f"{SIM}/{tag}_hold_{d}.json"
        if not os.path.exists(p):
            continue
        r = json.load(open(p))
        e = sum(1 for c in r["calls"] if c.get("error"))
        if e / max(1, len(r["calls"])) > POISON:
            continue
        out[d] = r
    return out


def metrics(rows: dict) -> dict | None:
    if not rows:
        return None
    tr = [t for r in rows.values() for t in r["trades"]]
    w = [t["pnl_usd"] for t in tr if t["pnl_usd"] > 0]
    l = [t["pnl_usd"] for t in tr if t["pnl_usd"] <= 0]
    net = sum(r["net_usd"] for r in rows.values())
    return {"days": len(rows), "net": net, "per_day": net / len(rows),
            "pos": sum(1 for r in rows.values() if r["net_usd"] > 0),
            "trades": len(tr), "tpd": len(tr) / len(rows),
            "wins": len(w), "win_sum": sum(w), "losses": len(l), "loss_sum": sum(l),
            "win_pct": 100.0 * len(w) / len(tr) if tr else 0.0,
            "payoff": abs((sum(w) / len(w)) / (sum(l) / len(l))) if w and l and sum(l) else 0.0}


def sha(p: str) -> str:
    try:
        return hashlib.sha256(open(p, "rb").read()).hexdigest()[:12]
    except Exception:
        return "—"


def iterations() -> list[int]:
    return sorted(int(f.split("rules_iter")[1].split(".")[0].split("_")[0])
                  for f in os.listdir(OUT)
                  if f.startswith("rules_iter") and f.endswith(".txt")
                  and "changelog" not in f)


def main() -> int:
    its = iterations()
    L: list[str] = []
    A = L.append
    A("# THE STRATEGY LEDGER — what changed, and what happened next")
    A("")
    A("> Operator, 2026-10-06: *\"we absolutely need to know why its improving or getting "
      "worse? all changes in logic and strategy need to be recorded\"* · *\"otherwise how do "
      "we measure success and failure etc\"*")
    A("")
    A("**⚠ REGENERATED BY `scripts/strategy_ledger.py`. Do not hand-edit** — a "
      "hand-maintained record drifts from what the code did, and then the account of the "
      "experiment becomes the least reliable artefact in it.")
    A("")
    A("## How success is measured, and the one thing this cannot measure")
    A("")
    A(f"The bar is in `docs/PROJECT_800_A_DAY.md`: **$800/day at 4 lots on the holdout**, "
      f"with trades/day 3-6, side accuracy ≥0.75 and leg capture ≥0.15. All four, on weeks "
      f"never trained on and never reviewed.")
    A("")
    A(f"**The noise floor is ${RUN_VARIANCE:,.0f}/day.** That is the measured spread of this "
      f"harness run twice on IDENTICAL inputs. Any iteration-to-iteration move smaller than "
      f"it is not evidence of learning, however tidy the story.")
    A("")
    A("**What cannot be measured here:** *which rule* caused a change. Each iteration "
      "rewrites up to ten rules at once and is run ONCE. That is correlation. Establishing "
      "cause needs the same week re-run with a single rule toggled and everything else held "
      "— a separate, more expensive experiment that has not been run. Every \"why\" below is "
      "therefore a DECOMPOSITION of where the money moved, not an attribution.")
    A("")

    prev_rows = None
    prev_it = None
    for it in its:
        rp = f"{OUT}/rules_iter{it}.txt"
        cp = f"{OUT}/rules_iter{it}_changelog.txt"
        rows = day_rows(f"loop{it}")
        m = metrics(rows)
        A(f"---")
        A("")
        A(f"## Iteration {it}")
        A("")
        A(f"- rule set: `rules_iter{it}.txt` · sha `{sha(rp)}` · "
          f"{len(open(rp).read())} chars" if os.path.exists(rp) else "- rule set: MISSING")
        if m:
            A(f"- holdout: **${m['per_day']:+,.0f}/day** over {m['days']} clean days "
              f"(${m['net']:+,.0f}) · {m['pos']}/{m['days']} days positive · "
              f"{m['tpd']:.1f} trades/day")
            A(f"- trades: {m['trades']} · win {m['win_pct']:.0f}% · "
              f"payoff {m['payoff']:.2f} · wins ${m['win_sum']:+,.0f} / "
              f"losses ${m['loss_sum']:+,.0f}")
        else:
            A("- holdout: **incomplete** — not scored")
        A("")

        # declared intent
        A("### What it said it was changing")
        A("")
        if os.path.exists(cp):
            txt = open(cp).read().strip()
            A("```")
            A(txt if txt else "[empty]")
            A("```")
        else:
            A("*No declared CHANGELOG — the requirement was added to `consolidate()` on "
              "2026-10-06 and applies from iteration 4 onward. For earlier iterations the "
              "change is RECONSTRUCTED below by `scripts/rule_diff.py`, which is weaker "
              "evidence: it is inference from prose, not the author stating intent.*")
        A("")

        # reconstructed diff
        if prev_it is not None:
            A(f"### What actually changed vs iteration {prev_it} (reconstructed)")
            A("")
            try:
                d = subprocess.run([sys.executable, f"{GB}/scripts/rule_diff.py",
                                    "--from", str(prev_it), "--to", str(it), "--text-only"],
                                   capture_output=True, text=True, timeout=120).stdout
                A("```")
                A(d.strip() or "[no output]")
                A("```")
            except Exception as e:
                A(f"*diff failed: {type(e).__name__}*")
            A("")

            # decomposition
            if m and prev_rows:
                pm = metrics(prev_rows)
                common = [d for d in HOLD if d in rows and d in prev_rows]
                if pm and common:
                    A(f"### Where the money moved (vs iteration {prev_it})")
                    A("")
                    A(f"| day | iter {prev_it} | iter {it} | change |")
                    A("|---|---|---|---|")
                    up = dn = 0
                    for d in common:
                        x = prev_rows[d]["net_usd"]
                        y = rows[d]["net_usd"]
                        if y > x:
                            up += 1
                        elif y < x:
                            dn += 1
                        A(f"| {d} | ${x:+,.0f} | ${y:+,.0f} | **${y - x:+,.0f}** |")
                    A("")
                    A(f"- **{up} days improved, {dn} days got worse.**")
                    dw = m["win_sum"] - pm["win_sum"]
                    dl = m["loss_sum"] - pm["loss_sum"]
                    A(f"- winners moved **${dw:+,.0f}**, losers moved **${dl:+,.0f}** — "
                      f"the change is {'in the LOSING tail' if abs(dl) > abs(dw) else 'in the WINNERS'}.")
                    delta = m["per_day"] - pm["per_day"]
                    A(f"- $/day moved **${delta:+,.0f}** against a ${RUN_VARIANCE:,.0f} noise "
                      f"floor → **{'above the floor' if abs(delta) > RUN_VARIANCE else 'INSIDE the floor, not evidence of learning'}**.")
                    A("")
                    # leave-one-out
                    A(f"**Leave-one-day-out** — how much of the lead rests on one session:")
                    A("")
                    flips = []
                    for d in common:
                        la = sum(prev_rows[k]["net_usd"] for k in common if k != d) / (len(common) - 1)
                        lb = sum(rows[k]["net_usd"] for k in common if k != d) / (len(common) - 1)
                        if (lb - la) * delta < 0:
                            flips.append((d, lb - la))
                    if flips:
                        for d, lead in flips:
                            A(f"- remove **{d}** and the verdict FLIPS (lead becomes "
                              f"${lead:+,.0f}/day) — that one day is load-bearing")
                    else:
                        A(f"- the direction survives removing any single day "
                          f"({len(common)} of {len(common)} hold)")
                    A("")
        prev_rows, prev_it = rows, it

    A("---")
    A("")
    A(f"*Generated {dt.datetime.now(dt.UTC):%Y-%m-%d %H:%M}Z from "
      f"`reports/recursive_loop/` and `reports/sim_week_recursive/`.*")
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    open(DOC, "w").write("\n".join(L) + "\n")
    print(f"wrote {DOC} — {len(L)} lines, iterations {its}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
